name: Test long

on:
  push:
    branches: [main, chore-workflows]
  workflow_dispatch:
    inputs:
      dolmos-options:
        description: "additional dolmos options"
        required: false
        type: string
        default: ""

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        cache-solver: ["", "--cache-solver"]
        testname:
          - "tests/solver"
          - "examples/simple"
          - "examples/invariants"
          - "examples/tokens/ERC20"
          - "examples/tokens/ERC721"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build image
        run: |
          docker build -t dolmos-image . --file packages/dolmos/Dockerfile

      - name: Print dolmos version
        run: docker run dolmos-image dolmos --version

      - name: Run pytest
        run: |
          docker run -v .:/workspace dolmos-image pytest -x -v tests/test_dolmos.py -k ${{ matrix.testname }} --dolmos-options='-st --solver-threads 3 ${{ matrix.cache-solver }} ${{ inputs.dolmos-options }}' -s --log-cli-level=
