name: Test FFI

on:
  push:
    branches: [main, chore-workflows]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
        - testname: "tests/ffi"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build image
        run: |
          docker build -t dolmos-image . --file packages/dolmos/Dockerfile

      - name: Print dolmos version
        run: docker run dolmos-image dolmos --version

      - name: Run pytest
        run: docker run -v .:/workspace dolmos-image pytest -v tests/test_dolmos.py -k ${{ matrix.testname }} --dolmos-options="--ffi -v -st"
